version: '2'
services:
  nginx:
    image: nginx:1.15-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
    - ./../build/resources/main/static:/usr/share/nginx/html
    - ./nginx/site-docker-local.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "9000:80"
